version: '3'
services:
  api:
    container_name: api-chat-zika
    build: .
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_started
  rabbitmq:
    container_name: rabbitmq-chat-zika
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "5671:5671"
